### ISSUE TITLE
0.2.0: Notes and checklist

### ISSUE THREAD

**Issue by joshbruce** [8fold/php-shoop#38]
See also #26 

- [x] ensure all trait methods use `Shoop::*` to return instance
- [ ] make sure test documentation classes at least reference the correct method
- [x] remove commented out code
- [x] verify correct namespaces
- [x] delete "broken" folders
